// Shared constants used by both game.js and multiplayer.js

window.GAME_CONSTANTS = {
    // Race
    RACE_COUNTDOWN_SECONDS: 5,
    RACE_FINISH_DISTANCE_METERS: 400,

    // Shift penalties
    SHIFT_PENALTY_BRAKE_LIGHT: 0.35,
    SHIFT_PENALTY_BRAKE_HEAVY: 0.6,
    SHIFT_PENALTY_DURATION_LIGHT: 0.2,
    SHIFT_PENALTY_DURATION_HEAVY: 0.38,
    SHIFT_PENALTY_TORQUE_LIGHT: 0.88,
    SHIFT_PENALTY_TORQUE_HEAVY: 0.74,

    // 3D World streaming
    STREAM_DIRECTION: -1,
    STREAM_SEGMENT_LENGTH: 30,
    STREAM_SEGMENT_COUNT: 3,
    STREAM_STREET_LIGHT_PAIRS: 3,
    STREAM_SKIP_INITIAL_LIGHT_PAIRS: 0,
    STREAM_DECORATION_COUNT: 16,
    STREAM_START_Z: -100,
    STREAM_RECYCLE_BEHIND_DISTANCE: 45,
    STREET_LIGHT_STEP: 20,
    DECORATION_STEP: 8,

    // Camera & Car base positions
    CAMERA_BASE_POS: { x: 8, y: 2.5, z: -125 },
    CAR_BASE_POS: { x: 2, y: -0.5, z: -122 },
};
